### ISSUE TITLE
[API] 부스 관리자페이지

### ISSUE THREAD

**Issue by bell2lee** [KMU-WINK/k-fop-festival-map-server#14]
- 부스 생성은 총학생회만
- 수정은 부스 관리자가 가능.
- 해시태그도 이때 만들자

@HO22 회원 기능 중 그룹 분리해서 사용하는 부분 알고 계신 것 있나요?

**Comment by HO22** [comment]
미리 퍼미션 그룹을 생성한 후, 유저에게 그 그룹을 적용시키면 될 듯 합니다.

https://docs.djangoproject.com/en/3.1/topics/auth/default/#groups
