### ISSUE TITLE
[로그인 정책] 익명 사용자 토큰인증 관련 모델 정의

### ISSUE THREAD

**Issue by bell2lee** [KMU-WINK/k-fop-festival-map-server#20]
# 방안
1. 익명 사용자 생성 요청 -> 사용자 생성 및 그룹 지정 -> API 인증

2.익명 사용자 생성 요청 -> 별도 토큰 모델에 사용자 생성 -> 커스텀 퍼미션을 이용한 API 인증

두 가지 방법이 있어보입니다.

# 차이점
1의 경우 group 을 분리해 퍼미션쪽 설정이 간단합니다. 회원생성 시 익명 사용자를 가입 시킵니다.(self recursive relation 이용하여 CASCADE 삭제 전파)
2의 경우 퍼미션을 커스텀으로 정의해 체크해야합니다. (기간에 따라 토큰 삭제) (이는 토큰 삭제가 곧 회원 삭제)

위 내용들 판단 해서 각자 의견 제시해주세요.

# 참고
- https://docs.djangoproject.com/en/3.1/topics/auth/default/#groups
- https://ssungkang.tistory.com/entry/Django-Token-%EC%9D%B8%EC%A6%9D-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0-TokenAuthentication

**Comment by easyandones** [comment]
1의 경우 대부분의 기능들이 django의 프레임워크에서 제공되고 있습니다. 이에 별다른 어려움 없이 추가 데이터만 OneToOne 필드로 간단하게 연결하면 됩니다.
또한 세션관리나 사용자 인증에서도 내장된 기능을 사용할 수 있어, 따로 수정하거나 작업할 부분 없이 전반적으로 효율적인 작업이 가능할 것 같습니다.

2의 경우 직접 모델을 생성하고 토큰을 발급/검증하며 세션, 보안 및 인증과 관련된 middleware 작업 등 직접 처리해야할 작업들이 많아질 것 같습니다.

사용자 model관리의 측면에서도 1의 경우가 조금 더 안정적이고 간단할 것 같습니다.

**Comment by sinpyo** [comment]
Drf에서 많은 기능들을 제공해주고 그중
Drf에서 제공해주는 permission으로 관리자 및 사용자를 구분해서 사용할 수 있고 필요에 따라 커스텀도 할 수 있습니다. User 관리 측면에서도 효율성을 고려해 1이 나은 것 같습니다.

**Comment by bell2lee** [comment]
1번으로 custom user model 정의 한 pull request 올렸습니다.

**Comment by Kim-tang2** [comment]
저도 1번이 좋다고 생각합니다. drf에서 지원해준다면 굳이 2번을 사용할 필요도 없고 신표님 말대로 커스텀도 가능하다면 ㅎㅎ 답은 정해졌네요 😉

**Comment by bell2lee** [comment]
커스텀 유저 모델에 관하여 : https://medium.com/@hckcksrl/django-%EC%BB%A4%EC%8A%A4%ED%85%80-%EC%9C%A0%EC%A0%80-%EB%AA%A8%EB%8D%B8-custom-user-model-b8487c0d150
